project_id = "eurjdhzdqlurvbgyeqgg"

[functions.signup-user]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
